[tool.poetry]
name = "djoser"
version = "1.0.9"  # managed by plugin
description = "REST implementation of Django authentication system."
authors = [
  "Sunscrapers <info@sunscrapers.com>",
]
maintainers = [
  "Dominik Kozaczko <dominik@kozaczko.info>",
]
license = "MIT"
classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Framework :: Django",
        "Framework :: Django :: 2.2",
        "Framework :: Django :: 3.1",
        "Framework :: Django :: 3.2",
        "Framework :: Django :: 4.0",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
]
repository = "https://github.com/sunscrapers/djoser"
documentation = "https://djoser.readthedocs.io/"
readme = "README.rst"
include = ["djoser/locale/**/*.mo"]


[tool.poetry.dependencies]
python = "^3.7"
importlib-metadata = {version = "^1.0", python = "<3.8"}
djangorestframework-simplejwt = "^5.0"
django-templated-mail = "^1.1.1"
social-auth-app-django = "^5.0.0"
coreapi = "^2.3.3"
asgiref = "^3.2.10"
pytest = {version = "^6.0.2", optional=true}
codecov = {version="^2.0.16", optional=true}
coverage = {version="^6.2", optional=true}
pytest-cov = {version="^3.0", optional=true}
pytest-django = {version="^4.5.2", optional=true}
pytest-pythonpath = {version="^0.7.3", optional=true}
djet = {version="^0.3.0", optional=true}
pytz = "^2021.3"
webauthn = {version="<1.0", optional=true}


[tool.poetry.group.dev.dependencies]
pyupgrade = "^2.31.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.7.1"
tox = "^3.20.0"
babel = "^2.8.0"
black = "^21.12b0"


[tool.poetry.extras]
test = [
  "pytest",
  "codecov",
  "coverage",
  "pytest-cov",
  "pytest-django",
  "pytest-pythonpath",
  "djet",
]
webauthn = [
    "webauthn",
]

[tool.black]
line-length = 88
target-version = ['py37', "py38", "py39", "py310"]
include = '\.pyi?$'
exclude = '''
(
  /(
      \.cache
    | \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.pytest_cache
    | \.tox
    | \.venv
    | __pycache__
    | _build
    | buck-out
    | build
    | dist
    | docs
    | migrations
  )/
)
'''


[tool.isort]
profile = "black"


[tool.pytest.ini_options]
minversion = "6.0"
DJANGO_SETTINGS_MODULE = "testproject.settings"
python_paths = "testproject"


[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "88"

[tool.poetry-version-plugin]
source = "init"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
